        $(function(){
            //异步提交表单
            $("#ajaxSubmit").on("click",function(){
                //console.log($(this));
                $("#formToUpdate").ajaxSubmit({
                    type:'post',
                    url:'insertMany.action',
                    success:function(data){
                    		alert(data);
                    },
                    error:function(XmlHttpRequest,textStatus,errorThrown){
                    	alert(XmlHttpRequest);
                    	alert(textStatus);
                    	alert(errorThrown);
                    }
                });
            });
        });